### PR TITLE
Adding game path to settings page 

### PR DESCRIPTION
**Pull request by Amaikokonut**
This is technically functional (to my knowledge) but a large amount of the pathfinding JS here was lazily copy-pasted from the local-page,js-- for the future is there a preferred way of handling that (linking one from the other, or having a shared file linked from both) that fits nicely/doesn't clash with the project structure you have in place already?

(Also I took the liberty of throwing in some padding because it looked a little crowded but I'm not too attached to it if you have another vision in mind.)

### CODE REVIEW

**Comment by JGantts** [comment]
Functions very well from what I can tell. And the padding looks good.

Could you refactor it though? So that the engine locator functions aren't copied. They could be centralized either in the settings-page folder or the engine-api folder. I'm leaning towards the settings folder.

**Comment by Amaikokonut** [comment]
Can do, thanks! The settings folder makes sense to me too.

**Comment by Amaikokonut** [comment]
Okay, I feel a *lot* better about how this works now. It's ready for re-review!

**Comment by JGantts** [comment]
Looks good to me!

**Pull request merged**
